### ISSUE TITLE
`npm install -g json-schema-generator` fails with `npm ERR! cb() never called!`

### ISSUE THREAD

**Issue by iki** [krg7880/json-schema-generator#4]
```
$ npm install -g json-schema-generator
...
npm http fetch GET http://npm-registry01.prd.nytimes.com/wordwrap/-/wordwrap-0.0.2.tgz
npm ERR! cb() never called!
```

> either ditch their npm-shrinkwrap.json from the published package, or to make sure that it's not pointing to their private registry when they publish the package to the public registry
~ @othiym23 at https://github.com/npm/npm/issues/7146#issuecomment-70358849

**Comment by krg7880** [comment]
This issue is now resolved

**Comment by iki** [comment]
thanks @krg7880!
